# Generated by Django 4.2.2 on 2023-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
